dist: trusty
sudo: required
language: bash
before_install:
- wget -O https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh
  | bash 
notifications:
  slack:
    rooms:
      secure: oYKc4kgRvhVCWcVxaMVQjFkd0Uh8gPt7qWbyuyKTBWd11gIcwBzuvIqhzxVLgdRMI5s6CvZv9ipQWkmfzAobS0++v4csQoID6vZKnX07FZRn8amVD7UC++xMMrxqX9o1hv9np3q7Kvu0sg9bPG9oxB/ZbsdVgsn5HzNHly7VV2hHMn9drWL4tfRXUmnPbACeRGZ8koglM6EQPXH9RI2yqj+p6UiZcfqGGI76hLLtHcGbVdEIUoJ410vqlsVOHtYEP57dg0irSXS2uxUj/ePiteI4p3kZNjHqb/PcIGmYLbHzwpmDARAJ8zam9NAx6d/e0Qwl0Q9OPNEXEVW9tHHKlP6CNN/ClvEIfn1P3zfpYf/LAwIHNCrSj96rnq/bT8i2FHvLCSzbBqOPTAjZ5QeLzRX+qO6dCquw3U5kSVV6lcd9x0EyHpwJfMjmVBdL81aLrg/6/z2i0muyG/VmRgAsYu+e8E/EE4CvUjoHDrfjI9YDXNoSM1t0F8MY9Q9jJ425Dib/mS0++FFr4v6wIt8M0mLDPc5ApTHWm3gPhitfoN3tlw9DliBl+NoSHhhMWVb1XrjbYEmvSndRCfRi2ULI3XBjX8s8ttv0PZmk9wQkoosnJBcpvrWaAv5cUiOy0jUfOv8OYVMLWVf+OMKNbVFO4eoeK5m5mhMcFiYjE2mu9AI=
